### ISSUE TITLE
Version?

### ISSUE THREAD

**Issue by mrjcleaver** [mcackay/confluence-helpers#1]
Hi Mark, thanks for sharing :)

What version of Confluence has this been tested against?

What security precautions should we take?

Thanks, M.

**Comment by mcackay** [comment]
Hi M - It's currently running against 5.5.x without issue. I am hoping to upgrade to the latest sometime this/next week so can advise if there's any issues. I'm not expecting there to be any as the interface with confluence is pretty thin, and would likely only be affected by a major change to the confluence auth/user system. /Mark

**Comment by mcackay** [comment]
Re: Security precautions - mmm - there's very little risk with this approach, as all we're really doing is presenting our own login form and tweaking the output. 

In fact, if I think about it, and you're just after an email or username approach - you could probably add some Javascript to the standard confluence header that detects the submit on the built-in login form, and does an ajax lookup if the user types an email in the username field, substitutes it with their username, before allowing the default form submit to complete.

But I wanted to be able to customise the look and feel a bit more and the 'messaging' and so for me, this was less intrusive and more easily manageable.

From a security perspective, I think you mainly need to look out for SQL injection in your arguments -- so provided you're quoting the input, etc it should be fine. I welcome anyone else's comments on that though.

/Mark

**Comment by mcackay** [comment]
I can confirm that this now also works with Confluence 5.6.6.
